# Generated by Django 5.2.7 on 2025-10-14 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('order_confirmed', 'Order Placed'), ('payment_successful', 'Payment Successful'), ('stock_updated', 'Stock Updated')], max_length=50)),
                ('recipient', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
