# Generated by Django 5.2.7 on 2025-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
