# Generated by Django 5.2.7 on 2025-10-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
