# Generated by Django 5.2.7 on 2025-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_buyer_email_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
